import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import '../globals.css';

import { getServerSession } from 'next-auth';
import { authOptions } from '@/auth/auth';
import { Footer, NavBar } from '@/components/shared';
import { ProfileSideBar } from '@/components/shared/profile/profile-side-bar';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Clicon',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className=''>
      <NavBar />
      <main className='bg-[#000] py-25 px-4 flex gap-4   min-h-[100vh] relative  justify-between '>
        <ProfileSideBar />

        <div className='w-full'>{children}</div>
      </main>
      <Footer />
    </div>
  );
}
